In [3]:
import cv2 as cv 

In [2]:
#read the image
image = cv.imread("../DATA/image1.jpg")


In [3]:
#convert the image to grayscale
gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
#print the image array
print(gray)



[[114 114 112 ... 165 165 165]
 [114 114 112 ... 165 165 165]
 [114 114 112 ... 165 165 165]
 ...
 [ 63  63  61 ... 211 211 211]
 [ 63  65  64 ... 216 215 214]
 [ 63  65  64 ... 216 215 214]]


In [4]:
print("")
#print the shape of the array which is of the form (height, width, number of channels)
print(gray.shape)


(682, 1024)


In [7]:
rgb_image = cv.imread("../DATA/rgb_image.jpg")
rgb_image = cv.cvtColor(rgb_image , cv.COLOR_BGR2RGB)

In [8]:
print(rgb_image)

[[[48 23 19]
  [47 22 18]
  [49 21 18]
  ...
  [ 2  3 23]
  [ 2  3 23]
  [ 2  3 23]]

 [[47 22 18]
  [47 22 18]
  [49 21 18]
  ...
  [ 3  4 24]
  [ 3  4 24]
  [ 3  4 24]]

 [[49 21 20]
  [48 20 19]
  [49 19 17]
  ...
  [ 3  4 24]
  [ 3  4 24]
  [ 3  4 24]]

 ...

 [[ 9  5 28]
  [ 9  5 28]
  [ 9  5 28]
  ...
  [13 10 27]
  [12  9 26]
  [12  9 26]]

 [[ 9  5 28]
  [ 9  5 28]
  [ 9  5 28]
  ...
  [11  9 23]
  [12 10 24]
  [13 11 25]]

 [[ 9  5 28]
  [ 9  5 28]
  [ 9  5 28]
  ...
  [14 12 26]
  [16 14 28]
  [19 17 31]]]


In [9]:
rgb_image.shape

(360, 639, 3)

In [10]:
#read the image
image = cv.imread("../DATA/colors.jpg")
#convert the image to RGB (images are read in BGR in OpenCV)
image = cv.cvtColor(image, cv.COLOR_BGR2RGB)
#split the image into its three channels
(R,G,B) = cv.split(image)
#create named windows for each of the images we are going to display
cv.namedWindow("Blue", cv.WINDOW_NORMAL)
cv.namedWindow("Green", cv.WINDOW_NORMAL)
cv.namedWindow("Red", cv.WINDOW_NORMAL)
#display the images
cv.imshow("Blue",B)
cv.imshow("Green", G)
cv.imshow("Red", R)
#write the images to disk
cv.imwrite("channel_red.jpg", R)
cv.imwrite("channel_green.jpg", G)
cv.imwrite("channel_blue.jpg", B)
if cv.waitKey(0):
    cv.destroyAllWindows()

In [4]:
#read the image
image = cv.imread("../DATA/colors.jpg")
#convert the image to RGB (images are read in BGR in OpenCV)
(b,g,r) = image[0,0]
print(f"At pixel (0,0), - Red: {r} , Green: {g}, Blue {b}")

At pixel (0,0), - Red: 42 , Green: 141, Blue 12


In [5]:
image[0,0] = (0,0, 255)
(b,g,r) = image[0,0]
print(f"At pixel (0,0), - Red: {r} , Green: {g}, Blue {b}")

At pixel (0,0), - Red: 255 , Green: 0, Blue 0


In [6]:
corner = image[0:100, 0:100]
cv.imshow("Corner", corner)

In [7]:
image[0:100, 0:100] = (0, 255, 0) 
cv.imshow("Updated", image)
cv.waitKey(0)

113

: 

## Drawing

In [2]:
import numpy as np
import cv2 as cv
canvas = np.zeros((300, 300, 3), dtype="uint8")

In [3]:
green = (0,255,0)
cv.line(canvas, (0,0), (300,300), green)
cv.imshow("Canvas" , canvas)
cv.waitKey(0)

113

In [4]:
red = (0,0,255)
cv.line(canvas, (300,0), (0,300), red, 3)
cv.imshow("Canvas" , canvas)
cv.waitKey(0)

113

In [6]:
cv.rectangle(canvas, (10, 10), (60, 60), green)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

113

In [7]:
cv.rectangle(canvas, (50, 200), (200, 225), red, 5)
cv.imshow("Canvas", canvas)
cv.waitKey(0)



113

In [8]:
blue = (255, 0, 0)
cv.rectangle(canvas, (200, 50), (225, 125), blue, -1)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

113

In [9]:

canvas = np.zeros((300, 300, 3), dtype = "uint8")
(centerX, centerY) = (canvas.shape[1] // 2, canvas.shape[0] // 2)
white = (255, 255, 255)
for r in range(0, 175, 25):
    cv.circle(canvas, (centerX, centerY), r, white)

cv.imshow("Canvas", canvas)
cv.waitKey(0)

113

In [10]:
for i in range(0, 25):
    radius = np.random.randint(5, high = 200)
    color = np.random.randint(0, high = 256, size = (3,)).tolist()
    pt = np.random.randint(0, high = 300, size = (2,))
    cv.circle(canvas, tuple(pt), radius, color, -1)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

113

: 